"""Achievement definitions for the gamification system."""

from database.gamification_models import AchievementCategory, BadgeTier


ACHIEVEMENT_DEFINITIONS = [
    # FIRST STEPS Category
    {
        'achievement_id': 'first_investigation',
        'name': 'First Steps',
        'description': 'Created your first investigation',
        'category': AchievementCategory.FIRST_STEPS,
        'tier': BadgeTier.BRONZE,
        'points_reward': 10,
        'xp_reward': 25,
        'requirement_type': 'count_investigations',
        'requirement_value': 1,
        'icon': '🔍',
        'badge_color': '#CD7F32',
        'unlock_message': 'Welcome to OSINT! You\'ve created your first investigation!'
    },
    {
        'achievement_id': 'first_scrape',
        'name': 'Data Collector',
        'description': 'Completed your first scraping job',
        'category': AchievementCategory.FIRST_STEPS,
        'tier': BadgeTier.BRONZE,
        'points_reward': 10,
        'xp_reward': 25,
        'requirement_type': 'count_scrapes',
        'requirement_value': 1,
        'icon': '🕷️',
        'badge_color': '#CD7F32',
        'unlock_message': 'Great! You\'ve successfully scraped your first data!'
    },
    {
        'achievement_id': 'first_finding',
        'name': 'Eagle Eye',
        'description': 'Discovered your first finding',
        'category': AchievementCategory.FIRST_STEPS,
        'tier': BadgeTier.BRONZE,
        'points_reward': 20,
        'xp_reward': 50,
        'requirement_type': 'count_findings',
        'requirement_value': 1,
        'icon': '👁️',
        'badge_color': '#CD7F32',
        'unlock_message': 'Excellent detective work! Your first finding!'
    },

    # EXPLORER Category
    {
        'achievement_id': '10_investigations',
        'name': 'Investigator',
        'description': 'Created 10 investigations',
        'category': AchievementCategory.EXPLORER,
        'tier': BadgeTier.SILVER,
        'points_reward': 50,
        'xp_reward': 100,
        'requirement_type': 'count_investigations',
        'requirement_value': 10,
        'icon': '🔎',
        'badge_color': '#C0C0C0',
        'unlock_message': 'You\'re becoming a skilled investigator!'
    },
    {
        'achievement_id': '50_investigations',
        'name': 'Master Investigator',
        'description': 'Created 50 investigations',
        'category': AchievementCategory.EXPLORER,
        'tier': BadgeTier.GOLD,
        'points_reward': 200,
        'xp_reward': 500,
        'requirement_type': 'count_investigations',
        'requirement_value': 50,
        'icon': '🏆',
        'badge_color': '#FFD700',
        'unlock_message': 'Amazing! You\'re a master investigator!'
    },
    {
        'achievement_id': '100_investigations',
        'name': 'OSINT Legend',
        'description': 'Created 100 investigations',
        'category': AchievementCategory.EXPLORER,
        'tier': BadgeTier.PLATINUM,
        'points_reward': 500,
        'xp_reward': 1000,
        'requirement_type': 'count_investigations',
        'requirement_value': 100,
        'icon': '👑',
        'badge_color': '#E5E4E2',
        'unlock_message': 'Legendary! You\'ve reached investigation mastery!'
    },
    {
        'achievement_id': '100_scrapes',
        'name': 'Web Crawler',
        'description': 'Completed 100 scraping jobs',
        'category': AchievementCategory.EXPLORER,
        'tier': BadgeTier.SILVER,
        'points_reward': 50,
        'xp_reward': 100,
        'requirement_type': 'count_scrapes',
        'requirement_value': 100,
        'icon': '🌐',
        'badge_color': '#C0C0C0',
        'unlock_message': 'You\'re a web crawling expert!'
    },
    {
        'achievement_id': '500_scrapes',
        'name': 'Scraping Master',
        'description': 'Completed 500 scraping jobs',
        'category': AchievementCategory.EXPLORER,
        'tier': BadgeTier.GOLD,
        'points_reward': 200,
        'xp_reward': 500,
        'requirement_type': 'count_scrapes',
        'requirement_value': 500,
        'icon': '🕸️',
        'badge_color': '#FFD700',
        'unlock_message': 'Incredible scraping skills!'
    },
    {
        'achievement_id': '1000_scrapes',
        'name': 'Data Harvester Supreme',
        'description': 'Completed 1000 scraping jobs',
        'category': AchievementCategory.EXPLORER,
        'tier': BadgeTier.DIAMOND,
        'points_reward': 1000,
        'xp_reward': 2000,
        'requirement_type': 'count_scrapes',
        'requirement_value': 1000,
        'icon': '💎',
        'badge_color': '#B9F2FF',
        'unlock_message': 'You\'re the ultimate data harvester!'
    },

    # DETECTIVE Category
    {
        'achievement_id': 'first_correlation',
        'name': 'Pattern Spotter',
        'description': 'Found your first correlation',
        'category': AchievementCategory.DETECTIVE,
        'tier': BadgeTier.BRONZE,
        'points_reward': 15,
        'xp_reward': 50,
        'requirement_type': 'count_correlations',
        'requirement_value': 1,
        'icon': '🔗',
        'badge_color': '#CD7F32',
        'unlock_message': 'Great eye! You\'ve spotted your first pattern!'
    },
    {
        'achievement_id': 'correlation_master',
        'name': 'Correlation Master',
        'description': 'Found 10 correlations',
        'category': AchievementCategory.DETECTIVE,
        'tier': BadgeTier.GOLD,
        'points_reward': 100,
        'xp_reward': 250,
        'requirement_type': 'count_correlations',
        'requirement_value': 10,
        'icon': '🧩',
        'badge_color': '#FFD700',
        'unlock_message': 'You excel at connecting the dots!'
    },
    {
        'achievement_id': 'correlation_expert',
        'name': 'Correlation Expert',
        'description': 'Found 50 correlations',
        'category': AchievementCategory.DETECTIVE,
        'tier': BadgeTier.PLATINUM,
        'points_reward': 500,
        'xp_reward': 1000,
        'requirement_type': 'count_correlations',
        'requirement_value': 50,
        'icon': '🎯',
        'badge_color': '#E5E4E2',
        'unlock_message': 'Your pattern recognition is unmatched!'
    },
    {
        'achievement_id': 'first_threat',
        'name': 'Threat Spotter',
        'description': 'Detected your first threat',
        'category': AchievementCategory.DETECTIVE,
        'tier': BadgeTier.BRONZE,
        'points_reward': 50,
        'xp_reward': 100,
        'requirement_type': 'count_threats',
        'requirement_value': 1,
        'icon': '⚠️',
        'badge_color': '#CD7F32',
        'unlock_message': 'Alert! You\'ve identified your first threat!'
    },
    {
        'achievement_id': 'threat_hunter',
        'name': 'Threat Hunter',
        'description': 'Detected 5 threats',
        'category': AchievementCategory.DETECTIVE,
        'tier': BadgeTier.SILVER,
        'points_reward': 200,
        'xp_reward': 400,
        'requirement_type': 'count_threats',
        'requirement_value': 5,
        'icon': '🛡️',
        'badge_color': '#C0C0C0',
        'unlock_message': 'You\'re keeping everyone safe!'
    },
    {
        'achievement_id': 'threat_master',
        'name': 'Threat Master',
        'description': 'Detected 20 threats',
        'category': AchievementCategory.DETECTIVE,
        'tier': BadgeTier.GOLD,
        'points_reward': 500,
        'xp_reward': 1000,
        'requirement_type': 'count_threats',
        'requirement_value': 20,
        'icon': '🦸',
        'badge_color': '#FFD700',
        'unlock_message': 'You\'re a cybersecurity hero!'
    },
    {
        'achievement_id': 'pattern_finder',
        'name': 'Pattern Finder',
        'description': 'Identified 20 patterns',
        'category': AchievementCategory.DETECTIVE,
        'tier': BadgeTier.SILVER,
        'points_reward': 100,
        'xp_reward': 200,
        'requirement_type': 'count_patterns',
        'requirement_value': 20,
        'icon': '📊',
        'badge_color': '#C0C0C0',
        'unlock_message': 'Your analytical skills are impressive!'
    },
    {
        'achievement_id': 'pattern_master',
        'name': 'Pattern Master',
        'description': 'Identified 100 patterns',
        'category': AchievementCategory.DETECTIVE,
        'tier': BadgeTier.GOLD,
        'points_reward': 500,
        'xp_reward': 1000,
        'requirement_type': 'count_patterns',
        'requirement_value': 100,
        'icon': '📈',
        'badge_color': '#FFD700',
        'unlock_message': 'You see patterns others miss!'
    },
    {
        'achievement_id': '50_findings',
        'name': 'Keen Observer',
        'description': 'Discovered 50 findings',
        'category': AchievementCategory.DETECTIVE,
        'tier': BadgeTier.SILVER,
        'points_reward': 100,
        'xp_reward': 250,
        'requirement_type': 'count_findings',
        'requirement_value': 50,
        'icon': '🔬',
        'badge_color': '#C0C0C0',
        'unlock_message': 'Your attention to detail is outstanding!'
    },
    {
        'achievement_id': '200_findings',
        'name': 'Master Detective',
        'description': 'Discovered 200 findings',
        'category': AchievementCategory.DETECTIVE,
        'tier': BadgeTier.GOLD,
        'points_reward': 400,
        'xp_reward': 800,
        'requirement_type': 'count_findings',
        'requirement_value': 200,
        'icon': '🕵️',
        'badge_color': '#FFD700',
        'unlock_message': 'You\'re a master detective!'
    },
    {
        'achievement_id': '500_findings',
        'name': 'Sherlock Holmes',
        'description': 'Discovered 500 findings',
        'category': AchievementCategory.DETECTIVE,
        'tier': BadgeTier.DIAMOND,
        'points_reward': 1000,
        'xp_reward': 2000,
        'requirement_type': 'count_findings',
        'requirement_value': 500,
        'icon': '🎩',
        'badge_color': '#B9F2FF',
        'unlock_message': 'Elementary! You\'re on par with Sherlock Holmes!'
    },

    # AUTOMATION Category
    {
        'achievement_id': 'automation_starter',
        'name': 'Automation Novice',
        'description': 'Automated your first task',
        'category': AchievementCategory.AUTOMATION,
        'tier': BadgeTier.BRONZE,
        'points_reward': 20,
        'xp_reward': 50,
        'requirement_type': 'count_automation',
        'requirement_value': 1,
        'icon': '🤖',
        'badge_color': '#CD7F32',
        'unlock_message': 'Welcome to the future! Your first automation!'
    },
    {
        'achievement_id': 'auto_100',
        'name': 'Automation Expert',
        'description': 'Automated 100 tasks',
        'category': AchievementCategory.AUTOMATION,
        'tier': BadgeTier.GOLD,
        'points_reward': 200,
        'xp_reward': 500,
        'requirement_type': 'count_automation',
        'requirement_value': 100,
        'icon': '⚙️',
        'badge_color': '#FFD700',
        'unlock_message': 'You\'re saving so much time with automation!'
    },
    {
        'achievement_id': 'auto_500',
        'name': 'Automation Master',
        'description': 'Automated 500 tasks',
        'category': AchievementCategory.AUTOMATION,
        'tier': BadgeTier.PLATINUM,
        'points_reward': 500,
        'xp_reward': 1000,
        'requirement_type': 'count_automation',
        'requirement_value': 500,
        'icon': '🚀',
        'badge_color': '#E5E4E2',
        'unlock_message': 'Automation mastery achieved!'
    },
    {
        'achievement_id': 'workflow_creator',
        'name': 'Workflow Designer',
        'description': 'Created your first workflow',
        'category': AchievementCategory.AUTOMATION,
        'tier': BadgeTier.BRONZE,
        'points_reward': 25,
        'xp_reward': 50,
        'requirement_type': 'count_workflows',
        'requirement_value': 1,
        'icon': '🔄',
        'badge_color': '#CD7F32',
        'unlock_message': 'Great! You\'ve created your first workflow!'
    },
    {
        'achievement_id': 'workflow_master',
        'name': 'Workflow Master',
        'description': 'Created 10 workflows',
        'category': AchievementCategory.AUTOMATION,
        'tier': BadgeTier.GOLD,
        'points_reward': 150,
        'xp_reward': 300,
        'requirement_type': 'count_workflows',
        'requirement_value': 10,
        'icon': '⚡',
        'badge_color': '#FFD700',
        'unlock_message': 'You\'ve mastered workflow automation!'
    },
    {
        'achievement_id': 'ai_assistant',
        'name': 'AI Enthusiast',
        'description': 'Used AI assistant 50 times',
        'category': AchievementCategory.AUTOMATION,
        'tier': BadgeTier.SILVER,
        'points_reward': 100,
        'xp_reward': 200,
        'requirement_type': 'count_ai_assists',
        'requirement_value': 50,
        'icon': '🧠',
        'badge_color': '#C0C0C0',
        'unlock_message': 'AI is your best friend now!'
    },
    {
        'achievement_id': 'ai_power_user',
        'name': 'AI Power User',
        'description': 'Used AI assistant 200 times',
        'category': AchievementCategory.AUTOMATION,
        'tier': BadgeTier.GOLD,
        'points_reward': 300,
        'xp_reward': 600,
        'requirement_type': 'count_ai_assists',
        'requirement_value': 200,
        'icon': '🌟',
        'badge_color': '#FFD700',
        'unlock_message': 'You\'re leveraging AI like a pro!'
    },

    # SOCIAL Category
    {
        'achievement_id': 'team_player',
        'name': 'Team Player',
        'description': 'Joined your first team',
        'category': AchievementCategory.SOCIAL,
        'tier': BadgeTier.BRONZE,
        'points_reward': 25,
        'xp_reward': 50,
        'requirement_type': 'special',
        'icon': '👥',
        'badge_color': '#CD7F32',
        'unlock_message': 'Welcome to the team!'
    },
    {
        'achievement_id': 'sharing_is_caring',
        'name': 'Sharing is Caring',
        'description': 'Shared 10 findings',
        'category': AchievementCategory.SOCIAL,
        'tier': BadgeTier.SILVER,
        'points_reward': 50,
        'xp_reward': 100,
        'requirement_type': 'count_shares',
        'requirement_value': 10,
        'icon': '📤',
        'badge_color': '#C0C0C0',
        'unlock_message': 'Thanks for sharing your knowledge!'
    },
    {
        'achievement_id': 'share_master',
        'name': 'Share Master',
        'description': 'Shared 50 findings',
        'category': AchievementCategory.SOCIAL,
        'tier': BadgeTier.GOLD,
        'points_reward': 200,
        'xp_reward': 400,
        'requirement_type': 'count_shares',
        'requirement_value': 50,
        'icon': '🎁',
        'badge_color': '#FFD700',
        'unlock_message': 'You\'re a generous knowledge sharer!'
    },
    {
        'achievement_id': 'collaborator',
        'name': 'Collaborator',
        'description': 'Collaborated on 5 investigations',
        'category': AchievementCategory.SOCIAL,
        'tier': BadgeTier.SILVER,
        'points_reward': 100,
        'xp_reward': 200,
        'requirement_type': 'count_collaborations',
        'requirement_value': 5,
        'icon': '🤝',
        'badge_color': '#C0C0C0',
        'unlock_message': 'Teamwork makes the dream work!'
    },
    {
        'achievement_id': 'collaboration_master',
        'name': 'Collaboration Master',
        'description': 'Collaborated on 25 investigations',
        'category': AchievementCategory.SOCIAL,
        'tier': BadgeTier.GOLD,
        'points_reward': 300,
        'xp_reward': 600,
        'requirement_type': 'count_collaborations',
        'requirement_value': 25,
        'icon': '🌟',
        'badge_color': '#FFD700',
        'unlock_message': 'You\'re a collaboration superstar!'
    },

    # EXPERT Category
    {
        'achievement_id': 'level_10',
        'name': 'Rising Star',
        'description': 'Reached level 10',
        'category': AchievementCategory.EXPERT,
        'tier': BadgeTier.SILVER,
        'points_reward': 100,
        'xp_reward': 0,
        'requirement_type': 'level',
        'requirement_value': 10,
        'icon': '⭐',
        'badge_color': '#C0C0C0',
        'unlock_message': 'You\'re on your way to greatness!'
    },
    {
        'achievement_id': 'level_25',
        'name': 'OSINT Professional',
        'description': 'Reached level 25',
        'category': AchievementCategory.EXPERT,
        'tier': BadgeTier.GOLD,
        'points_reward': 250,
        'xp_reward': 0,
        'requirement_type': 'level',
        'requirement_value': 25,
        'icon': '🌟',
        'badge_color': '#FFD700',
        'unlock_message': 'You\'re a professional OSINT analyst!'
    },
    {
        'achievement_id': 'level_50',
        'name': 'OSINT Master',
        'description': 'Reached level 50',
        'category': AchievementCategory.EXPERT,
        'tier': BadgeTier.PLATINUM,
        'points_reward': 500,
        'xp_reward': 0,
        'requirement_type': 'level',
        'requirement_value': 50,
        'icon': '👑',
        'badge_color': '#E5E4E2',
        'unlock_message': 'You\'ve achieved OSINT mastery!'
    },
    {
        'achievement_id': 'osint_master',
        'name': 'OSINT Grandmaster',
        'description': 'Reached level 100',
        'category': AchievementCategory.EXPERT,
        'tier': BadgeTier.DIAMOND,
        'points_reward': 1000,
        'xp_reward': 0,
        'requirement_type': 'level',
        'requirement_value': 100,
        'icon': '💎',
        'badge_color': '#B9F2FF',
        'unlock_message': 'Legendary! You\'re an OSINT Grandmaster!'
    },
    {
        'achievement_id': 'speed_demon',
        'name': 'Speed Demon',
        'description': 'Completed investigation in under 1 hour',
        'category': AchievementCategory.EXPERT,
        'tier': BadgeTier.GOLD,
        'points_reward': 200,
        'xp_reward': 400,
        'requirement_type': 'time',
        'requirement_value': 3600,  # seconds
        'icon': '⚡',
        'badge_color': '#FFD700',
        'unlock_message': 'Lightning fast! You completed that investigation in record time!'
    },
    {
        'achievement_id': 'perfectionist',
        'name': 'Perfectionist',
        'description': '100% accuracy on 10 investigations',
        'category': AchievementCategory.EXPERT,
        'tier': BadgeTier.PLATINUM,
        'points_reward': 400,
        'xp_reward': 800,
        'requirement_type': 'special',
        'requirement_data': {'perfect_investigations': 10},
        'icon': '✨',
        'badge_color': '#E5E4E2',
        'unlock_message': 'Perfect! Your attention to detail is impeccable!'
    },

    # SPECIAL Achievements
    {
        'achievement_id': 'early_adopter',
        'name': 'Early Adopter',
        'description': 'Joined in the first month',
        'category': AchievementCategory.SPECIAL,
        'tier': BadgeTier.GOLD,
        'points_reward': 500,
        'xp_reward': 1000,
        'requirement_type': 'special',
        'icon': '🎖️',
        'badge_color': '#FFD700',
        'is_secret': True,
        'unlock_message': 'Thank you for being an early adopter!'
    },
    {
        'achievement_id': 'night_owl',
        'name': 'Night Owl',
        'description': 'Completed 10 investigations between midnight and 6 AM',
        'category': AchievementCategory.SPECIAL,
        'tier': BadgeTier.SILVER,
        'points_reward': 100,
        'xp_reward': 200,
        'requirement_type': 'special',
        'requirement_data': {'night_investigations': 10},
        'icon': '🦉',
        'badge_color': '#C0C0C0',
        'is_secret': True,
        'unlock_message': 'Burning the midnight oil!'
    },
    {
        'achievement_id': 'streak_master',
        'name': 'Streak Master',
        'description': '30 day login streak',
        'category': AchievementCategory.SPECIAL,
        'tier': BadgeTier.GOLD,
        'points_reward': 300,
        'xp_reward': 600,
        'requirement_type': 'streak',
        'requirement_value': 30,
        'icon': '🔥',
        'badge_color': '#FFD700',
        'unlock_message': 'You\'re on fire! 30 days strong!'
    },
    {
        'achievement_id': 'century_streak',
        'name': 'Century Streak',
        'description': '100 day login streak',
        'category': AchievementCategory.SPECIAL,
        'tier': BadgeTier.DIAMOND,
        'points_reward': 1000,
        'xp_reward': 2000,
        'requirement_type': 'streak',
        'requirement_value': 100,
        'icon': '💯',
        'badge_color': '#B9F2FF',
        'unlock_message': 'Incredible dedication! 100 days!'
    },
]
